DROP TABLE IF EXISTS Client;
CREATE TABLE Client (
    id INT PRIMARY KEY AUTO_INCREMENT,
    userid INT NOT NULL,
    veterinaryCenterId INT NOT NULL,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(20),
    extraInfo TEXT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (userid) REFERENCES User(id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
    FOREIGN KEY (veterinaryCenterId) REFERENCES VeterinaryCenter(id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);