DROP TABLE IF EXISTS PetClient;
CREATE TABLE PetClient (
    id INT PRIMARY KEY AUTO_INCREMENT,
    petId INT NOT NULL,
    clientId INT NOT NULL,
    extraFields TEXT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (petId) REFERENCES Pet(id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
    FOREIGN KEY (clientId) REFERENCES Client(id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);